/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGrupoRouteImport } from './routes/_authenticated/grupo'
import { Route as AuthenticatedForoRouteImport } from './routes/_authenticated/foro'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrupoRoute = AuthenticatedGrupoRouteImport.update({
  id: '/grupo',
  path: '/grupo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForoRoute = AuthenticatedForoRouteImport.update({
  id: '/foro',
  path: '/foro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/foro': typeof AuthenticatedForoRoute
  '/grupo': typeof AuthenticatedGrupoRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/premium': typeof AuthenticatedPremiumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/foro': typeof AuthenticatedForoRoute
  '/grupo': typeof AuthenticatedGrupoRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/premium': typeof AuthenticatedPremiumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/foro': typeof AuthenticatedForoRoute
  '/_authenticated/grupo': typeof AuthenticatedGrupoRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/admin'
    | '/contacts'
    | '/foro'
    | '/grupo'
    | '/history'
    | '/map'
    | '/premium'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/admin'
    | '/contacts'
    | '/foro'
    | '/grupo'
    | '/history'
    | '/map'
    | '/premium'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/_authenticated/admin'
    | '/_authenticated/contacts'
    | '/_authenticated/foro'
    | '/_authenticated/grupo'
    | '/_authenticated/history'
    | '/_authenticated/map'
    | '/_authenticated/premium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupo': {
      id: '/_authenticated/grupo'
      path: '/grupo'
      fullPath: '/grupo'
      preLoaderRoute: typeof AuthenticatedGrupoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foro': {
      id: '/_authenticated/foro'
      path: '/foro'
      fullPath: '/foro'
      preLoaderRoute: typeof AuthenticatedForoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedForoRoute: typeof AuthenticatedForoRoute
  AuthenticatedGrupoRoute: typeof AuthenticatedGrupoRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedForoRoute: AuthenticatedForoRoute,
  AuthenticatedGrupoRoute: AuthenticatedGrupoRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
